"""Metrics types — token, run, and comparison metrics.

Defines the measurement structures used to track API usage,
investigation performance, and approach comparisons.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class TokenMetrics:
    """Tracks token consumption for a single API call.

    Attributes:
        input_tokens: Tokens sent to the model.
        output_tokens: Tokens generated by the model.
        total_tokens: Sum of input and output tokens.
        provider: Provider name (e.g. 'openai', 'anthropic').
        model: Model identifier used.
    """

    input_tokens: int = 0
    output_tokens: int = 0
    total_tokens: int = 0
    provider: str = ""
    model: str = ""


@dataclass
class RunMetrics:
    """Metrics for a single investigation run.

    Attributes:
        tokens_used: Total tokens consumed.
        files_read: Number of source files read.
        iterations: Number of agent iterations performed.
        time_seconds: Wall-clock time in seconds.
        found_root_cause: Whether a root cause was identified.
    """

    tokens_used: int = 0
    files_read: int = 0
    iterations: int = 0
    time_seconds: float = 0.0
    found_root_cause: bool = False


@dataclass
class ComparisonMetrics:
    """Side-by-side comparison of naive vs. guided runs.

    Attributes:
        naive: Metrics from the naive approach run.
        guided: Metrics from the graph-guided approach run.
        token_savings_pct: Percentage of tokens saved.
        file_read_savings_pct: Percentage of file reads saved.
        iteration_savings_pct: Percentage of iterations saved.
    """

    naive: RunMetrics = field(default_factory=RunMetrics)
    guided: RunMetrics = field(default_factory=RunMetrics)
    token_savings_pct: float = 0.0
    file_read_savings_pct: float = 0.0
    iteration_savings_pct: float = 0.0


@dataclass
class ComparisonReport:
    """Complete comparison report between naive and guided approaches.

    Attributes:
        metrics: Side-by-side comparison metrics.
        narrative: Human-readable summary of findings.
        token_savings: Absolute token savings count.
    """

    metrics: ComparisonMetrics = field(default_factory=ComparisonMetrics)
    narrative: str = ""
    token_savings: int = 0
